# Use an official lightweight Python image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the application files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set UTF-8 encoding for stdout
ENV PYTHONIOENCODING utf-8

# Run the script in an infinite loop to restart after failure
CMD while true; do python3 mastodon_stream.py; sleep 5; done
