FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONIOENCODING utf-8

# Running the script in an infinite loop to restart after failure
CMD while true; do python3 mastodon_stream.py; sleep 5; done
