FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONIOENCODING=utf-8

CMD ["sh", "-c", "while true; do python consumer.py; echo 'Consumer crashed. Restarting in 5 seconds...'; sleep 5; done"]
